### ISSUE TITLE
server side search doesn't work

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#209]
1. Go to https://sonarwhal.com/docs/
2. Type `x-ua-compatible` (or anything) and press the search button

You will land in the 404 page

**Comment by qzhou1607** [comment]
Will take a look at this.

**Comment by qzhou1607** [comment]
@molant @alrra this works locally. I wonder if it is due to the `_config.yml` not copied again (like what happened in https://github.com/sonarwhal/sonarwhal.com/issues/183). I don't have the credentials to connect via ftp. Could one of you help to check when you have time? (or send me the credentials again... Thanks!)
