### ISSUE TITLE
Style Changelog Page

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#212]
- Add icons for headers (i.e. Bug fixes, Breaking changes, etc)

- adjust list/bullet points

- Improve layout/type/color use for readability

**Comment by ststimac** [comment]
Proposed Changelog design update:

![changelog_09222017](https://user-images.githubusercontent.com/18073131/30757399-73d41154-9f83-11e7-9513-88e9fa91c58d.png)

**Comment by ststimac** [comment]
I'm going to build a changelog template to implement these changes, will need @qzhou1607 or someone else to help finish off the template w/handlebars updates. Ideally changelog content should be pulled into the page like documentation pages are right now. If that's an issue let me know, and I will just edit the markdown file but for the sake of upkeep, a template would probably be best.

**Comment by molant** [comment]
> Ideally changelog content should be pulled into the page like documentation pages are right now. If that's an issue let me know

The changelog is updated automatically on each release so manually updating it to put the images is not an option. We will make it work in a post process or something :)

**Comment by ststimac** [comment]
ok sounds good :) just wanted to make sure building a template would work in some way.

**Comment by qzhou1607** [comment]
If we are using a template for the changelog rather than using the markdown, it probably makes more sense to generate a `.json` file in https://github.com/sonarwhal/sonar/blob/f5c0218bdf5ef85921f032edece6c903abda9d07/scripts/release.ts#L66 instead of keeping information in a `.md` file. Parsing markdown file here to extract the information to fill the template seems a redundant task. What do you think? @molant  @alrra ?

**Comment by molant** [comment]
We need the markdown so people can see it directly from github so doing the markdown --> json --> html is probably the only option.

Good think is that the format of our changelog is predictable so it should be relatively easy to transform (2 spaces between releases, etc.).
