### ISSUE TITLE
Unexpected Token at <

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonarwhal.com#270]
An issue reported in https://github.com/sonarwhal/sonar/issues/598 originally.
> I was unable to see the output of the following test:
https://sonarwhal.com/scanner/bcd43ac0-963f-4920-b831-7287cbb7a866
>
>It displays:
Unexpected token < in JSON at position 0
>
>I would have expected to see the results

**Comment by grantkemp** [comment]
I noticed there was an issue analysing the SSL report - I wonder if the errant JSON was coming from that Qualys api? 
```ERROR
Error in sonar analyzing this rule
To learn more visit   Qualys SSL Labs```

**Comment by molant** [comment]
> I wonder if the errant JSON was coming from that Qualys api?

Maybe, although I don't think so. Rules are executed elsewhere so if there's something wrong with SSL Labs it will break the worker processing that rule and not the site.

I think the problem was with too many requests to the DB because hitting refresh will eventually get you the right results. I've updated the throughput and we've done some changes in the online-service to process things faster that hopefully should help with that.
