### ISSUE TITLE
Add more space between details/summary?

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#371]
This is how it looks like now [link](https://sonarwhal.com/docs/user-guide/rules/http-compression/#how-to-configure-the-server-to-pass-this-rule):

![image](https://user-images.githubusercontent.com/606594/35315354-cda65cd8-0080-11e8-9be5-b272a2b4298b.png)

Other sections look like this:

![image](https://user-images.githubusercontent.com/606594/35315368-e53afa3e-0080-11e8-9ced-a8101dcddf60.png)

**Comment by ststimac** [comment]
@molant just a heads up, when I clicked the link above, it didn't take me to the section, it just took me to the top of the page despite having #howtoconfiguretheservertopassthisrule at the end of the hyperlink.

**Comment by molant** [comment]
We updated the way the ids are generated and this one was using the old format. I've updated my comment and it should take you to the right place now.

**Comment by ststimac** [comment]
This is a bit lengthy but I have a few questions due to the way the documentation pages are output into HTML.

How often do you think the `details` element will be used in the documentation? Will there also be multiple instances of it on one page, under different subheadings? Would `details` only every appear below `h2` subheadings? or could it be below an `h3` or `p` element?

I'm trying to gauge the best way to apply styling to these because of the way the documentation pages are rendered. For example, if there _are_ going to be multiple instances of the details element on a page, say 2 below 1 subheading, and 2 below another subheading, in the hierarchy of the page, they have the same parent so I can't use :first-child or :nth-child as it would only apply to the very first details element. 

Ideally the `details` elements would be wrapped like the following: 

`<div class="details-class">`
    `<details></details>`
    `<details></details>`
`</div>`

And then a margin applied to the details-class. 

### Is there a preference on how to proceed? 

1. Modify HTML: We just wrap `<details>` in a wrapper div, apply margin to div. 
2. Leave HTML/Markdown alone and have a few different selectors: `h2 + details`, `h3 + details`, `p + details` etc.

**Comment by molant** [comment]
@seaotta there are a few rules that have details/summary.

Right now there are only 2 entries but we hope to add more in the future (e.g.: "how to nginx").

I don't think we will use them in another context, at least for now, and I'd like to avoid writing any html in the markdown.
Hope that helps!

**Comment by ststimac** [comment]
OK, I will target with a few different CSS selectors. Also, I don't know how you tagged my separate github account but seaotta isn't my main github username.
