### ISSUE TITLE
Discuss the future of https://sonarwhal.com/docs/user-guide/rules/

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#391]
Now that the rules are no longer included in `sonarwhal`, I think https://sonarwhal.com/docs/user-guide/rules/ should be automatically generated, instead of having it in `packages/sonarwhal/docs/user-guide/rules/index.md` (see also: https://github.com/sonarwhal/sonarwhal/pull/822).

**Comment by molant** [comment]
Was thinking the same. We probably need to rethink the layout of the page.

**Comment by qzhou1607** [comment]
Maybe we can use this https://hexo.io/api/generator.html#Archive-Page from Hexo. We will need to keep the category information somewhere, maybe in the frontmatter of each rule doc, or in `_config.yml`.

**Comment by molant** [comment]
Adding @ststimac to the conversation. This is something we need to address sooner rather than later.
We are going to have probably a new category `development` (or similar) with all the typescript, webpack, etc. rules and there are going to be in @TheLarkInn's words "hundreds of them" 🙄

**Comment by ststimac** [comment]
Are you talking about updating the individual rule pages or the overview page with all the categories?

We should probably redo the side table of contents if there are going to be "hundreds" of new rules.

**Comment by ststimac** [comment]
I've got an idea for the layout. I'll do a quick mockup for this on Monday.

**Comment by ststimac** [comment]
Proposal for the rules landing page:

![screen shot 2018-03-05 at 1 34 03 pm](https://user-images.githubusercontent.com/18073131/37001002-f7c8ddf6-2079-11e8-928b-aaed73d2e2a4.png)

Show first 5 rules under each category and then any one that has more than that can be expanded to show the rest for a category.

**Comment by molant** [comment]
Can we have somewhere how many rules for each category we have?
For the navigation on the left, is it going to be blank, have a list with all the rules, list the categories?

I'm not convinced that not listing all the rules directly is the best idea. Maybe we could have a landing for categories and then a landing for each category?

**Comment by molant** [comment]
In this page we will have the description of each category, how many rules we have for each one, and link to the category (don't think we need more space than the one you've allocated already), and in the category landing page something similar to what we have right now?

**Comment by molant** [comment]
And I just saw https://github.com/sonarwhal/sonarwhal.com/issues/403 re the navigation on the left side

**Comment by ststimac** [comment]
Two other options:       
![rules-lp-03052018-01](https://user-images.githubusercontent.com/18073131/37113602-adb115e4-21fa-11e8-87d4-552df3f3dc23.png)

![rules-lp-03052018-02](https://user-images.githubusercontent.com/18073131/37113603-add42fde-21fa-11e8-81a0-02096a76af5e.png)

**Comment by molant** [comment]
I like the titles of the first option (the one with the icon inline with the name of the category) mixed with the second option that has the count of rules and view all in the same line.

**Comment by ststimac** [comment]
new mockup
![screen shot 2018-03-08 at 3 28 20 pm](https://user-images.githubusercontent.com/18073131/37182320-8c27a4c4-22e5-11e8-883e-19c5b9d6b547.png)

**Comment by molant** [comment]
Ship it!

**Comment by molant** [comment]
Maybe not hundreds, but there could be quite a few for a given category (a few tens).

**Comment by ststimac** [comment]
![screen shot 2018-03-09 at 2 28 33 pm](https://user-images.githubusercontent.com/18073131/37232992-42147bac-23a6-11e8-8e73-6be4a9d9ca75.png)

Well depending on how many rules we start accumulating, if the list gets long enough, it should probably overflow into a multi-column layout, but we're probably not there yet. I will set it up though so that if we reach so many lines of rules, it will overflow into the next column.

**Comment by molant** [comment]
👍

**Comment by ststimac** [comment]
So from a responsive standpoint, the two column layout works better. At smaller browser widths, the 3 column layout gets messy because the rule category titles are mostly pretty long, and end up being longer than the column and breaking onto a new line. It just doesn't flow well. I will be going with the following layout. Also the icons are missing because none of the images are loading when I run `npm run steph`

I will also make a note in the PR but the page title should be RULE Categories, not plural like we currently have: Rules Categories.

<img width="1420" alt="screen shot 2018-03-15 at 10 27 15 am" src="https://user-images.githubusercontent.com/18073131/37480070-86f3d6e8-283b-11e8-8ba0-ca15533bcdfc.png">
